app/routes/wbs.py
from flask import Blueprint, render_template, session, redirect, url_for, jsonify, request
from app.models.wbs_header import WbsHeader
from app.models.wbs_detail import WbsDetail
from app.models.wbs_item import WbsItem
from app import db

wbs_bp = Blueprint('wbs', __name__)

@wbs_bp.route('/wbs')
def wbs():
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    wbs = WbsHeader.query.all()
    return render_template('wbs/index.html', wbs=wbs)

@wbs_bp.route('/wbs/store', methods=['POST'])
def store():
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    wbs = WbsHeader()
    print(request.form['wbs_name'])
    wbs.name = request.form['wbs_name']
    db.session.add(wbs)
    db.session.commit()

    return redirect(url_for('wbs.wbs'))

@wbs_bp.route('/wbs/detail/<int:id>')
def detail(id):
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    wbs = WbsHeader.query.get(id)
    wbs_details = WbsDetail.query.filter_by(wbs_header_id=id).all()
    return render_template('wbs/_detail.html', wbs=wbs, wbs_details=wbs_details)

@wbs_bp.route('/wbs/update/<int:id>', methods=['POST'])
def update_wbs(id):
    # Get the WBS name from the form data
    updated_name = request.form['wbs_edit']

    # Find the WBS by ID and update its name
    wbs = WbsHeader.query.get(id)
    if wbs:
        wbs.name = updated_name
        db.session.commit()
        return redirect(url_for('wbs.wbs'))
    else:
        return jsonify({'message': 'WBS not found.'}), 404
    
@wbs_bp.route('/wbs/delete/<int:id>', methods=['POST'])
def delete(id):
    wbs = WbsHeader.query.get(id)
    db.session.delete(wbs)
    db.session.commit()

    return jsonify({'message': 'Data deleted successfully.'})

@wbs_bp.route('/wbs/detail/store', methods=['POST'])
def store_detail():
    wbs_detail = WbsDetail()
    wbs_detail.wbs_header_id = request.form['wbs_header_id']
    wbs_detail.code = request.form['wbs_code']
    wbs_detail.name = request.form['wbs_name']
    db.session.add(wbs_detail)
    db.session.commit()

    return redirect(url_for('wbs.detail', id=request.form['wbs_header_id']))

@wbs_bp.route('/wbs/detail/update/<int:id>', methods=['POST'])
def update_detail(id):
    wbs_detail = WbsDetail.query.get(id)
    wbs_detail.code = request.form['wbs_code_edit']
    wbs_detail.name = request.form['wbs_name_edit']
    db.session.commit()

    return redirect(url_for('wbs.detail', id=request.form['wbs_header_id_edit']))

@wbs_bp.route('/wbs/detail/delete/<int:id>', methods=['POST'])
def delete_detail(id):
    wbs_detail = WbsDetail.query.get(id)
    db.session.delete(wbs_detail)
    db.session.commit()

    return jsonify({'message': 'Data deleted successfully.'})

@wbs_bp.route('/wbs/<int:id>/detail/<int:detail_id>/item')
def detail_item(id, detail_id):
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    wbs = WbsHeader.query.get(id)
    wbs_detail = WbsDetail.query.get(detail_id)
    wbs_items = WbsItem.query.filter_by(wbs_detail_id=detail_id).all()
    return render_template('wbs/item/_detail.html', wbs=wbs, wbs_detail=wbs_detail, wbs_items=wbs_items)

@wbs_bp.route('/wbs/detail/item/store', methods=['POST'])
def store_item():
    wbs_item = WbsItem()
    wbs_item.wbs_detail_id = request.form['wbs_detail_id']
    wbs_item.code = request.form['wbs_item_code']
    wbs_item.name = request.form['wbs_item_name']
    db.session.add(wbs_item)
    db.session.commit()

    return redirect(url_for('wbs.detail_item', id=request.form['wbs_header_id'], detail_id=request.form['wbs_detail_id']))

@wbs_bp.route('/wbs/detail/item/delete/<int:id>', methods=['POST'])
def delete_item(id):
    wbs_item = WbsItem.query.get(id)
    db.session.delete(wbs_item)
    db.session.commit()

    return jsonify({'message': 'Data deleted successfully.'})

@wbs_bp.route('/wbs/detail/item/update/<int:id>', methods=['POST'])
def update_item(id):
    wbs_item = WbsItem.query.get(id)
    wbs_item.code = request.form['wbs_item_code_edit']
    wbs_item.name = request.form['wbs_item_name_edit']
    db.session.commit()

    return redirect(url_for('wbs.detail_item', id=request.form['wbs_header_id_edit'], detail_id=request.form['wbs_detail_id_edit']))

app/templates/wbs/_detail.html
{% extends 'base.html' %}

{% block content %}
<!-- Content Wrapper START -->
<div class="main-content">
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
                <div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                    <i class="anticon anticon-file-image-o font-size-30 text-primary">
                    </i>
                </div>
                <div class="m-l-15">
                    <h4 class="m-b-0">{{ wbs.name }}</h4>
                    <p class="text-muted m-b-0">ID: {{ wbs.id }}</p>
                </div>
            </div>

            <!-- Back link -->
            <div>
                <a href="{{ url_for('wbs.wbs') }}" class="btn btn-link">Back</a>
            </div>
        </div>

        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-overview">Detail</a>
            </li>
        </ul>
    </div>
    <div class="container-fluid">
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-overview">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h4 class="card-title">WBS Detail</h4>
                            <div class="dropdown dropdown-animated scale-left">
                                <button class="btn btn-sm btn-default" type="button" data-toggle="modal"
                                    data-target="#createModal">
                                    <i class="anticon anticon-plus"></i>
                                    Create
                                </button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table" id="data-table">
                                <thead>
                                    <tr>
                                        <th>
                                            Code
                                        </th>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Created At
                                        </th>
                                        <th>
                                            Updated At
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for wb in wbs_details %}
                                    <tr>
                                        <td>
                                            {{ wb.code }}
                                        </td>
                                        <td>
                                            {{ wb.name }}
                                        </td>
                                        <td>
                                            {{ wb.created_at }}
                                        </td>
                                        <td>
                                            {{ wb.updated_at }}
                                        </td>
                                        <td>
                                            <a href="{{ url_for('wbs.detail_item', id=wbs.id, detail_id=wb.id) }}"
                                                class="badge badge-green" style="font-size: 15px;" title="Detail">
                                                <i class="anticon anticon-eye"></i>
                                            </a>
                                            <a href="#" class="badge badge-blue btn-edit-wbs" data-toggle="modal"
                                                data-target="#editModal" data-wbs-id="{{ wb.id }}"
                                                data-wbs-code="{{ wb.code }}" data-wbs-name="{{ wb.name }}"
                                                style="font-size: 15px;" title="Edit">
                                                <i class="anticon anticon-edit"></i>
                                            </a>
                                            <a href="#" class="badge badge-red btn-delete-wbs" style="font-size: 15px;"
                                                title="Delete" data-wbs-id="{{ wb.id }}">
                                                <i class="anticon anticon-delete"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>
                                            Code
                                        </th>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Created At
                                        </th>
                                        <th>
                                            Updated At
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content Wrapper END -->
<!-- Create Modal -->
<div class="modal fade" id="createModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{{ url_for('wbs.store_detail') }}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="createModalTitle">Create</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" class="form-control" id="wbs_code" name="wbs_code" placeholder="WBS Code">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="wbs_name" name="wbs_name" placeholder="WBS Name">
                    </div>
                    <input type="text" id="wbs_header_id" name="wbs_header_id" value="{{ wbs.id }}" hidden>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="editModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form id="editForm" action="" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalTitle">Edit</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" class="form-control" id="wbs_code_edit" name="wbs_code_edit"
                            placeholder="WBS Code">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="wbs_name_edit" name="wbs_name_edit"
                            placeholder="WBS Name">
                    </div>
                    <input type="text" id="wbs_header_id_edit" name="wbs_header_id_edit" value="{{ wbs.id }}" hidden>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Bower JS -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<script>
    // Fungsi untuk mengirimkan request AJAX ketika tombol delete diklik
    document.addEventListener('DOMContentLoaded', function () {
        const deleteButtons = document.querySelectorAll('.btn-delete-wbs');

        deleteButtons.forEach(function (button) {
            button.addEventListener('click', function () {
                const wbsId = button.getAttribute('data-wbs-id');

                // Kirim request AJAX menggunakan fetch API
                fetch(`/wbs/detail/delete/${wbsId}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                })
                    .then((response) => response.json())
                    .then((data) => {
                        // Tampilkan pesan sukses atau gagal
                        alert(data.message);

                        // Jika berhasil, redirect ke halaman index proyek
                        if (data.message === 'Data deleted successfully.') {
                            window.location.href = '{{ url_for('wbs.detail', id=wbs.id) }}';
                        }
                    })
                    .catch((error) => {
                        console.error('Error:', error);
                    });
            });
        });
    });
</script>

<script>
    function updateWbsName(wbsId, updatedCode, updatedName) {
        const formData = new FormData();
        formData.append('wbs_code_edit', updatedCode);
        formData.append('wbs_name_edit', updatedName);

        fetch(`/wbs/detail/update/${wbsId}`, {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
            .then((response) => response.json())
            .then((data) => {
                alert(data.message);
                if (data.message === 'Data updated successfully.') {
                    // Reload the table after updating the wbs name
                    fetchWbsNames();
                }
            })
            .catch((error) => {
                console.error('Error:', error);
            });
    }

    function fetchWbsNames() {
        fetch('{{ url_for("wbs.detail", id=wbs.id ) }}', {
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
            .then((response) => response.text())
            .then((data) => {
                // Update the table body with the new data
                document.getElementById('data-table').getElementsByTagName('tbody')[0].innerHTML = data;
            })
            .catch((error) => {
                console.error('Error:', error);
            });
    }

    // Function to display the edit modal with the selected wbs name data
    function displayEditModal(wbsId, wbsCode, wbsName) {
        const editModalTitle = document.getElementById('editModalTitle');
        const wbsCodeInput = document.getElementById('wbs_code_edit');
        const wbsNameInput = document.getElementById('wbs_name_edit');
        const editForm = document.getElementById('editForm');

        // Set the modal title
        editModalTitle.innerHTML = 'Edit'

        // Set the wbs name data to the input field
        wbsCodeInput.value = wbsCode;
        wbsNameInput.value = wbsName;

        // Update the form action to include the wbs ID for submission
        editForm.action = `/wbs/detail/update/${wbsId}`;
    }

    document.addEventListener('DOMContentLoaded', function () {
        const editButtons = document.querySelectorAll('.btn-edit-wbs');

        editButtons.forEach(function (button) {
            button.addEventListener('click', function () {
                const wbsId = button.getAttribute('data-wbs-id');
                const wbsCode = button.getAttribute('data-wbs-code');
                const wbsName = button.getAttribute('data-wbs-name');

                // Display the edit modal with the selected wbs name data
                displayEditModal(wbsId, wbsCode, wbsName);
            });
        });
    });
</script>
{% endblock %}

app/templates/wbs/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Content Wrapper START -->
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">WBS</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="{{ url_for('wbs.wbs') }}" class="breadcrumb-item"><i
                        class="anticon anticon-home m-r-5"></i>WBS</a>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <h5>WBS</h5>
                <div>
                    <button class="btn btn-sm btn-default" type="button" data-toggle="modal" data-target="#createModal">
                        <i class="anticon anticon-plus"></i>
                        Create
                    </button>
                </div>
            </div>
            <div class="m-t-25">
                <table id="data-table" class="table">
                    <thead>
                        <tr>
                            <th>
                                ID
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Created At
                            </th>
                            <th>
                                Updated At
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for wb in wbs %}
                        <tr>
                            <td>
                                {{ wb.id }}
                            </td>
                            <td>
                                {{ wb.name }}
                            </td>
                            <td>
                                {{ wb.created_at }}
                            </td>
                            <td>
                                {{ wb.updated_at }}
                            </td>
                            <td>
                                <a href="{{ url_for('wbs.detail', id=wb.id) }}" class="badge badge-green"
                                    style="font-size: 15px;" title="Detail">
                                    <i class="anticon anticon-eye"></i>
                                </a>
                                <a href="#" class="badge badge-blue btn-edit-wbs" data-toggle="modal"
                                    data-target="#editModal" data-wbs-id="{{ wb.id }}" data-wbs-name="{{ wb.name }}"
                                    style="font-size: 15px;" title="Edit">
                                    <i class="anticon anticon-edit"></i>
                                </a>
                                <a href="#" class="badge badge-red btn-delete-wbs" style="font-size: 15px;"
                                    title="Delete" data-wbs-id="{{ wb.id }}">
                                    <i class="anticon anticon-delete"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>
                                ID
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Created At
                            </th>
                            <th>
                                Updated At
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Content Wrapper END -->
<!-- Create Modal -->
<div class="modal fade" id="createModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{{ url_for('wbs.store') }}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="createModalTitle">Create</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" id="wbs_name" name="wbs_name" placeholder="WBS Name">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="editModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form id="editForm" action="" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalTitle">Edit</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" id="wbs_edit" name="wbs_edit" placeholder="WBS Name">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Bower JS -->
<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<script>
    // Fungsi untuk mengirimkan request AJAX ketika tombol delete diklik
    document.addEventListener('DOMContentLoaded', function () {
        const deleteButtons = document.querySelectorAll('.btn-delete-wbs');

        deleteButtons.forEach(function (button) {
            button.addEventListener('click', function () {
                const wbsId = button.getAttribute('data-wbs-id');

                // Kirim request AJAX menggunakan fetch API
                fetch(`/wbs/delete/${wbsId}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                })
                    .then((response) => response.json())
                    .then((data) => {
                        // Tampilkan pesan sukses atau gagal
                        alert(data.message);

                        // Jika berhasil, redirect ke halaman index proyek
                        if (data.message === 'Data deleted successfully.') {
                            window.location.href = '{{ url_for('wbs.wbs') }}';
                        }
                    })
                    .catch((error) => {
                        console.error('Error:', error);
                    });
            });
        });
    });
</script>

<script>
    function updateWbsName(wbsId, updatedName) {
        const formData = new FormData();
        formData.append('wbs_edit', updatedName);

        fetch(`/wbs/update/${wbsId}`, {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
            .then((response) => response.json())
            .then((data) => {
                alert(data.message);
                if (data.message === 'Data updated successfully.') {
                    // Reload the table after updating the wbs name
                    fetchWbsNames();
                }
            })
            .catch((error) => {
                console.error('Error:', error);
            });
    }

    function fetchWbsNames() {
        fetch('{{ url_for("wbs.wbs") }}', {
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
            .then((response) => response.text())
            .then((data) => {
                // Update the table body with the new data
                document.getElementById('data-table').getElementsByTagName('tbody')[0].innerHTML = data;
            })
            .catch((error) => {
                console.error('Error:', error);
            });
    }

    // Function to display the edit modal with the selected wbs name data
    function displayEditModal(wbsId, wbsName) {
        const editModalTitle = document.getElementById('editModalTitle');
        const wbsNameInput = document.getElementById('wbs_edit');
        const editForm = document.getElementById('editForm');

        // Set the modal title
        editModalTitle.innerHTML = 'Edit';

        // Set the wbs name data to the input field
        wbsNameInput.value = wbsName;

        // Update the form action to include the wbs ID for submission
        editForm.action = `/wbs/update/${wbsId}`;
    }

    document.addEventListener('DOMContentLoaded', function () {
        const editButtons = document.querySelectorAll('.btn-edit-wbs');

        editButtons.forEach(function (button) {
            button.addEventListener('click', function () {
                const wbsId = button.getAttribute('data-wbs-id');
                const wbsName = button.getAttribute('data-wbs-name');

                // Display the edit modal with the selected wbs name data
                displayEditModal(wbsId, wbsName);
            });
        });
    });
</script>

{% endblock %}