app/models/project.py
from app import db

class Project(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    type = db.Column(db.String(255))
    location = db.Column(db.String(255))
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    revit_file = db.Column(db.String(255))
    excel_file = db.Column(db.String(255))
    photo_file = db.Column(db.String(255))
    revit_file_size = db.Column(db.String(10))
    excel_file_size = db.Column(db.String(10))
    photo_file_size = db.Column(db.String(10))
    revit_link = db.Column(db.String(255))

    wbs_headers = db.relationship('WbsHeaderProject', backref='project', lazy='dynamic', cascade='all, delete-orphan')

app/routes/project.py
from flask import Blueprint, render_template, session, redirect, url_for, request, jsonify
from werkzeug.utils import secure_filename
import os
from app import db, create_app
from app.models.project import Project
from app.models.sheet_name import SheetName
from app.models.wbs_header import WbsHeader
from app.models.wbs_detail import WbsDetail
from app.models.wbs_item import WbsItem
from app.models.wbs_header_project import WbsHeaderProject
from app.models.wbs_detail_project import WbsDetailProject
from app.models.wbs_item_project import WbsItemProject
import pandas as pd
from sqlalchemy import and_, asc
from datetime import datetime

project_bp = Blueprint('project', __name__)


def convert_size(size_bytes):
    # Konversi ukuran bytes menjadi KB atau MB
    KB = 1024
    MB = KB * 1024

    if size_bytes >= MB:
        size = "{:.2f} MB".format(size_bytes / MB)
    elif size_bytes >= KB:
        size = "{:.2f} KB".format(size_bytes / KB)
    else:
        size = "{:.2f} bytes".format(size_bytes)

    return size

@project_bp.route('/')
def index():
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    projects = Project.query.all()
    return render_template('project/index.html', projects=projects)


@project_bp.route('/project/create')
def create():
    if 'email' not in session:
        return redirect(url_for('auth.login'))
    
    return render_template('project/_create.html')


@project_bp.route('/project/detail/<int:id>')
def detail(id):
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    project = Project.query.get(id)
    headers = WbsHeaderProject.query.filter(WbsHeaderProject.project_id == id).order_by(asc(WbsHeaderProject.created_at)).all()
    return render_template('project/_detail.html', project=project, headers=headers)

@project_bp.route('/project/<int:id>/wbs/<int:header_id>/detail')
def wbs_detail(id, header_id):
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    project = Project.query.get(id)
    header = WbsHeaderProject.query.get(header_id)
    details = WbsDetailProject.query.filter(WbsDetailProject.wbs_header_project_id == header.id).all()
    
    for detail in details:
        items = WbsItemProject.query.filter(WbsItemProject.wbs_detail_project_id == detail.id).all()
        
        detail_items = []  # List to hold the items for the current detail
        for item in items:
            item_data = {
                'id': item.id,
                'name': item.name,
                'created_at': item.created_at,
                'updated_at': item.updated_at,
                # Add other item properties as needed
            }
            detail_items.append(item_data)
        
        detail.items = detail_items  # Assign the list of items to the detail

    return render_template('project/wbs/_detail.html', project=project, header=header, details=details)


@project_bp.route('/project/edit/<int:id>')
def edit(id):
    if 'email' not in session:
        return redirect(url_for('auth.login'))

    project = Project.query.get(id)
    return render_template('project/_edit.html', project=project)


@project_bp.route('/project/store', methods=['POST'])
def store():
    app = create_app()  # Get access to the app object

    # Get form data
    name = request.form['inputName']
    type = request.form['inputType']
    location = request.form['inputLocation']
    start_date = request.form['inputStartDate']
    end_date = request.form['inputEndDate']
    revit_link = request.form['inputLinkRevit']

    # Get uploaded files
    revit_file = request.files['inputUploadRevit']
    excel_file = request.files['inputUploadExcel']
    photo_file = request.files['inputUploadPhoto']

    # Cek ukuran file
    file_size_revit = len(revit_file.read())
    file_size_excel = len(excel_file.read())
    file_size_photo = len(photo_file.read())

    # Kembali ke awal file
    revit_file.seek(0)
    excel_file.seek(0)
    photo_file.seek(0)

    # Konversi ukuran file ke KB atau MB
    revit_file_size_formatted = convert_size(file_size_revit)
    excel_file_size_formatted = convert_size(file_size_excel)
    photo_file_size_formatted = convert_size(file_size_photo)

    # Get file extensions
    revit_ext = os.path.splitext(revit_file.filename)[1]
    excel_ext = os.path.splitext(excel_file.filename)[1]
    photo_ext = os.path.splitext(photo_file.filename)[1]

    # Remove existing extensions
    revit_filename_base = os.path.splitext(revit_file.filename)[0]
    excel_filename_base = os.path.splitext(excel_file.filename)[0]
    photo_filename_base = os.path.splitext(photo_file.filename)[0]

    # Generate secure filenames with proper extensions
    revit_filename = secure_filename(revit_filename_base) + revit_ext
    excel_filename = secure_filename(excel_filename_base) + excel_ext
    photo_filename = secure_filename(photo_filename_base) + photo_ext

    # Save files to the desired folder
    revit_file.save(os.path.join(app.config['UPLOAD_FOLDER'], revit_filename))
    excel_file.save(os.path.join(app.config['UPLOAD_FOLDER'], excel_filename))
    photo_file.save(os.path.join(app.config['UPLOAD_FOLDER'], photo_filename))

    # Get the full path of the uploaded Excel file
    excel_file_full_path = os.path.join(app.config['UPLOAD_FOLDER'], excel_filename)

    # Create a new project object
    project = Project(
        name=name,
        type=type,
        location=location,
        start_date=start_date,
        end_date=end_date,
        revit_file=revit_filename,
        excel_file=excel_filename,
        photo_file=photo_filename,
        revit_file_size=revit_file_size_formatted,
        excel_file_size=excel_file_size_formatted,
        photo_file_size=photo_file_size_formatted,
        revit_link=revit_link,
    )

    # Save project to the database
    db.session.add(project)
    db.session.commit()

    # Access the ID of the newly inserted project
    project_id = project.id

    wbs = store_multiple_sheet(project_id, excel_file_full_path)

    return jsonify({'message': 'Data stored successfully.'})


@project_bp.route('/project/delete/<int:id>', methods=['POST'])
def delete_project(id):
    app = create_app()  # Get access to the app object

    project = Project.query.get(id)

    if project:
        # Hapus file upload dari sistem file jika file ada
        if project.excel_file:
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], project.excel_file)
            if os.path.exists(file_path):
                os.remove(file_path)

        if project.revit_file:
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], project.revit_file)
            if os.path.exists(file_path):
                os.remove(file_path)

        if project.photo_file:
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], project.photo_file)
            if os.path.exists(file_path):
                os.remove(file_path)

        # Hapus data proyek dari database
        db.session.delete(project)
        db.session.commit()

        return jsonify({'message': 'Data deleted successfully.'})
    else:
        return jsonify({'message': 'Project not found.'}), 404
    

@project_bp.route('/project/update/<int:id>', methods=['POST'])
def update(id):
    app = create_app()

    project = Project.query.get(id)

    if project:
        # Get form data
        name = request.form['inputName']
        type = request.form['inputType']
        location = request.form['inputLocation']
        start_date = request.form['inputStartDate']
        end_date = request.form['inputEndDate']
        revit_link = request.form['inputLinkRevit']

        # Get uploaded files
        revit_file = request.files['inputUploadRevit']
        excel_file = request.files['inputUploadExcel']
        photo_file = request.files['inputUploadPhoto']

        if revit_file.filename != '':
            # Hapus file lama dari sistem file
            if project.revit_file:
                file_path = os.path.join(app.config['UPLOAD_FOLDER'], project.revit_file)
                if os.path.exists(file_path):
                    os.remove(file_path)

            # Cek ukuran file
            file_size_revit = len(revit_file.read())

            # Kembali ke awal file
            revit_file.seek(0)

            # Konversi ukuran file ke KB atau MB
            revit_file_size_formatted = convert_size(file_size_revit)

            # Get file extensions
            revit_ext = os.path.splitext(revit_file.filename)[1]

            # Remove existing extensions
            revit_filename_base = os.path.splitext(revit_file.filename)[0]

            # Generate secure filenames with proper extensions
            revit_filename = secure_filename(revit_filename_base) + revit_ext

            # Save file to the desired folder
            revit_file.save(os.path.join(app.config['UPLOAD_FOLDER'], revit_filename))

            # Update project object
            project.revit_file = revit_filename
            project.revit_file_size = revit_file_size_formatted

        if excel_file.filename != '':
            # Hapus file lama dari sistem file
            if project.excel_file:
                file_path = os.path.join(app.config['UPLOAD_FOLDER'], project.excel_file)
                if os.path.exists(file_path):
                    os.remove(file_path)

            # Cek ukuran file
            file_size_excel = len(excel_file.read())

            # Kembali ke awal file
            excel_file.seek(0)

            # Konversi ukuran file ke KB atau MB
            excel_file_size_formatted = convert_size(file_size_excel)

            # Get file extensions
            excel_ext = os.path.splitext(excel_file.filename)[1]

            # Remove existing extensions
            excel_filename_base = os.path.splitext(excel_file.filename)[0]

            # Generate secure filenames with proper extensions

app/templates/project/_create.html
{% extends 'base.html' %}

{% block content %}
<!-- Content Wrapper START -->
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Project</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="{{ url_for('project.index') }}" class="breadcrumb-item"><i
                        class="anticon anticon-home m-r-5"></i>Project</a>
                <a class="breadcrumb-item active" href="{{ url_for('project.create') }}">Create</a>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <h5>Project</h5>
                <div>
                    <a href="{{ url_for('project.index') }}" class="btn btn-sm btn-default"><i class="anticon anticon-arrow-left"></i>
                        Back</a>
                </div>
            </div>
            <p></p>
            <div class="m-t-25">
                <form id="projectForm" enctype="multipart/form-data">
                    <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputName" name="inputName" placeholder="Name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputType" class="col-sm-2 col-form-label">Type</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="inputType" id="inputType">
                                <option value="Jembatan Beton">Jembatan Beton</option>
                                <option value="Jembatan Baja">Jembatan Baja</option>
                                <option value="Jembatan Komposit">Jembatan Komposit</option>
                                <option value="Gedung">Gedung</option>
                                <option value="Jalan">Jalan</option>
                                <option value="Bendungan">Bendungan</option>
                                <option value="Other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputLocation" class="col-sm-2 col-form-label">Location</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputLocation" name="inputLocation"
                                placeholder="Location">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputStartDate" class="col-sm-2 col-form-label">Start Date</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" id="inputStartDate" name="inputStartDate"
                                placeholder="Start Date">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputEndDate" class="col-sm-2 col-form-label">End Date</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" id="inputEndDate" name="inputEndDate"
                                placeholder="End Date">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUploadRevit" class="col-sm-2 col-form-label">Upload Revit</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" id="inputUploadRevit" name="inputUploadRevit"
                                placeholder="Upload Revit">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUploadExcel" class="col-sm-2 col-form-label">Upload Excel</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" id="inputUploadExcel" name="inputUploadExcel"
                                placeholder="Upload Excel">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUploadPhoto" class="col-sm-2 col-form-label">Upload Photo</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" id="inputUploadPhoto" name="inputUploadPhoto"
                                placeholder="Upload Excel">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputLinkRevit" class="col-sm-2 col-form-label">Link Revit</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputLinkRevit" name="inputLinkRevit"
                                placeholder="Link Revit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-footer text-left">
            <button type="button" class="btn btn-primary" onclick="saveProject()">Save</button>
        </div>
    </div>
</div>
<!-- Content Wrapper END -->

<script>
    function saveProject() {
        const form = document.getElementById('projectForm');
        const formData = new FormData(form);

        // Disabling the "Save" button
        const saveButton = document.querySelector('.card-footer button');
        saveButton.disabled = true;
        saveButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Saving...';

        const xhr = new XMLHttpRequest();
        xhr.open('POST', '{{ url_for("project.store") }}');
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhr.onload = function () {
            if (xhr.status === 200) {
                // Response handling logic here
                console.log(xhr.responseText);

                // Re-enable the "Save" button
                saveButton.disabled = false;
                saveButton.innerHTML = 'Save';

                // Show success message or alert
                alert('Data stored successfully.');

                // Reload the page
                window.location.reload();
            }
        };
        xhr.send(formData);
    }
</script>
{% endblock %}

app/templates/project/_edit.html
{% extends 'base.html' %}

{% block content %}
<!-- Content Wrapper START -->
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Project</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="{{ url_for('project.index') }}" class="breadcrumb-item"><i
                        class="anticon anticon-home m-r-5"></i>Project</a>
                <a href="{{ url_for('project.detail', id=project.id) }}" class="breadcrumb-item">Detail {{ project.name }}</a>
                <a class="breadcrumb-item active" href="{{ url_for('project.edit', id=project.id) }}">Edit</a>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Project</h4>
            <p></p>
            <div class="m-t-25">
                <form id="projectForm" enctype="multipart/form-data">
                    <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputName" name="inputName" placeholder="Name" value="{{ project.name }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputType" class="col-sm-2 col-form-label">Type</label>
                        <div class="col-sm-10">
                            <div class="col-sm-10">
                                <select class="form-control" name="inputType" id="inputType">
                                    <option value="Jembatan Beton" {% if project.type == 'Jembatan Beton' %}selected{% endif %}>Jembatan Beton</option>
                                    <option value="Jembatan Baja" {% if project.type == 'Jembatan Baja' %}selected{% endif %}>Jembatan Baja</option>
                                    <option value="Jembatan Komposit" {% if project.type == 'Jembatan Komposit' %}selected{% endif %}>Jembatan Komposit</option>
                                    <option value="Gedung" {% if project.type == 'Gedung' %}selected{% endif %}>Gedung</option>
                                    <option value="Jalan" {% if project.type == 'Jalan' %}selected{% endif %}>Jalan</option>
                                    <option value="Bendungan" {% if project.type == 'Bendungan' %}selected{% endif %}>Bendungan</option>
                                    <option value="Other" {% if project.type == 'Other' %}selected{% endif %}>Other</option>
                                </select>
                            </div>
                        </div>
                    </div>                    
                    <div class="form-group row">
                        <label for="inputLocation" class="col-sm-2 col-form-label">Location</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputLocation" name="inputLocation"
                                placeholder="Location" value="{{ project.location }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputStartDate" class="col-sm-2 col-form-label">Start Date</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" id="inputStartDate" name="inputStartDate"
                                placeholder="Start Date" value="{{ project.start_date }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputEndDate" class="col-sm-2 col-form-label">End Date</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" id="inputEndDate" name="inputEndDate"
                                placeholder="End Date" value="{{ project.end_date }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUploadRevit" class="col-sm-2 col-form-label">Upload Revit</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" id="inputUploadRevit" name="inputUploadRevit"
                                placeholder="Upload Revit" value="{{ project.upload_revit }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUploadExcel" class="col-sm-2 col-form-label">Upload Excel</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" id="inputUploadExcel" name="inputUploadExcel"
                                placeholder="Upload Excel" value="{{ project.upload_excel }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputUploadPhoto" class="col-sm-2 col-form-label">Upload Photo</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" id="inputUploadPhoto" name="inputUploadPhoto"
                                placeholder="Upload Excel" value="{{ project.upload_photo }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputLinkRevit" class="col-sm-2 col-form-label">Link Revit</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputLinkRevit" name="inputLinkRevit"
                                placeholder="Link Revit" value="{{ project.revit_link }}">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-footer text-left">
            <button type="button" class="btn btn-primary" onclick="updateProject()">Update</button>
        </div>
    </div>
</div>
<!-- Content Wrapper END -->

<script>
    function updateProject() {
        const form = document.getElementById('projectForm');
        const formData = new FormData(form);

        // Disabling the "Update" button during the request
        const updateButton = document.querySelector('.card-footer button');
        updateButton.disabled = true;
        updateButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Updating...';

        const xhr = new XMLHttpRequest();
        const projectId = {{ project.id }}; // Get the project ID
        const url = `/project/update/${projectId}`; // Correct route URL with the project ID
        xhr.open('POST', url);
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhr.onload = function () {
            if (xhr.status === 200) {
                // Response handling logic here
                console.log(xhr.responseText);

                // Re-enable the "Update" button
                updateButton.disabled = false;
                updateButton.innerHTML = 'Update';

                // Show success message or alert
                alert('Data updated successfully.');

                // Reload the page
                window.location.reload();
            }
        };
        xhr.send(formData);
    }
</script>
{% endblock %}

app/templates/project/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Content Wrapper START -->
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Project</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="{{ url_for('project.index') }}" class="breadcrumb-item"><i
                        class="anticon anticon-home m-r-5"></i>Project</a>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <h5>Project</h5>
                <div>
                    <a href="{{ url_for('project.create') }}" class="btn btn-sm btn-default">
                        <i class="anticon anticon-plus"></i>
                        Create</a>
                </div>
            </div>
            <div class="m-t-25">
                <table id="data-table" class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Location</th>
                            <th>Start date</th>
                            <th>End Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                        <tr>
                            <td>{{ project.name }}</td>
                            <td>{{ project.type }}</td>
                            <td>{{ project.location }}</td>
                            <td>{{ project.start_date }}</td>
                            <td>{{ project.end_date }}</td>
                            <td>
                                <a href="{{ url_for('project.detail', id=project.id) }}" class="badge badge-cyan"
                                    style="font-size: 15px;" title="Detail"><i class="anticon anticon-eye"></i></a>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Location</th>
                            <th>Start date</th>
                            <th>End Date</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Content Wrapper END -->
{% endblock %}